/************************************************************************************
* <auto-generated>
*     此代码由T4工具自动生成。 By Harry
*     对此文件的更改可能会导致不正确的行为，并且如果
*     重新生成代码，这些更改将会丢失。
* </auto-generated>
/************************************************************************************/
using ModelToSql.Model;
using ModelToSql;
using Easy.Framework.Core.Domain.Repositories;
using System.Collections.Generic;
namespace IModelRespoity
{    
    /// <summary>
    /// 公司名称仓储
    /// </summary>
    public interface ISys_CompanyRepository:IRepository<Sys_Company>
	{
	  
	}
    /// <summary>
    /// 仓储
    /// </summary>
    public interface ISys_lcyRepository:IRepository<Sys_lcy>
	{
	  
	}
    /// <summary>
    /// 角色仓储
    /// </summary>
    public interface ISys_UserRepository:IRepository<Sys_User>
	{
	  
	}
}
