/************************************************************************************
* <auto-generated>
*     此代码由T4工具自动生成。 By Harry
*     对此文件的更改可能会导致不正确的行为，并且如果
*     重新生成代码，这些更改将会丢失。
* </auto-generated>
/************************************************************************************/
using ModelToSql;
using System.Collections.Generic;
using ModelToSql.Model;
using IModelRespoity;
using Easy.Framework.Data.EF;
using Easy.Framework.Data.EF.Repositories;
namespace ModelRespoity
{    
    /// <summary>
    /// 公司名称仓储
    /// </summary>
    public partial class Sys_CompanyRepository:Repository<Sys_Company>, ISys_CompanyRepository
	{
	    public Sys_CompanyRepository(IDbContext dbContext)
            : base(dbContext)
        {

        }
	}
    /// <summary>
    /// 仓储
    /// </summary>
    public partial class Sys_lcyRepository:Repository<Sys_lcy>, ISys_lcyRepository
	{
	    public Sys_lcyRepository(IDbContext dbContext)
            : base(dbContext)
        {

        }
	}
    /// <summary>
    /// 角色仓储
    /// </summary>
    public partial class Sys_UserRepository:Repository<Sys_User>, ISys_UserRepository
	{
	    public Sys_UserRepository(IDbContext dbContext)
            : base(dbContext)
        {

        }
	}
}
