/************************************************************************************
* <auto-generated>
*     此代码由T4工具自动生成。 By Harry
*     对此文件的更改可能会导致不正确的行为，并且如果
*     重新生成代码，这些更改将会丢失。
* </auto-generated>
/************************************************************************************/
using ModelToSql;
using System.Collections.Generic;
using ModelToSql.Model;
using IModelRespoity;
using Easy.Framework.Data.EF;
using Easy.Framework.Data.EF.Repositories;
using Easy.Framework.Core.Application.Services;
using Application;
using System;
namespace IModelRespoity
{    
    /// <summary>
    /// 公司名称仓储
    /// </summary>
    public interface ISys_CompanyService:IApplicationService
	{
	   HttpPage<Sys_Company> getdata();
	    void SoftDelete(Guid id);
		 void Save(Sys_Company entity);
	}
    /// <summary>
    /// 部门仓储
    /// </summary>
    public interface ISys_DepartService:IApplicationService
	{
	   HttpPage<Sys_Depart> getdata();
	    void SoftDelete(Guid id);
		 void Save(Sys_Depart entity);
	}
    /// <summary>
    /// 仓储
    /// </summary>
    public interface ISys_lcyService:IApplicationService
	{
	   HttpPage<Sys_lcy> getdata();
	    void SoftDelete(Guid id);
		 void Save(Sys_lcy entity);
	}
    /// <summary>
    /// 角色仓储
    /// </summary>
    public interface ISys_UserService:IApplicationService
	{
	   HttpPage<Sys_User> getdata();
	    void SoftDelete(Guid id);
		 void Save(Sys_User entity);
	}
}
